new_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oferty.urls')),
    path('', include('uzytkownicy.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

oferty/urls.py
from django.urls import path
from . import views
from .views import OfertaDetailView, OfertaCreateView, OfertaUpdateView, OfertaDeleteView,\
                   KomentarzCreateView, KomentarzUpdateView, KomentarzDeleteView

urlpatterns = [
    path('', views.glowna, name='glowna'),
    path('oferta/<int:pk>', OfertaDetailView.as_view(), name='oferta_szczegoly'),
    path('oferta/nowa', OfertaCreateView.as_view(), name='oferta_utworz'),
    path('oferta/<int:pk>/aktualizuj', OfertaUpdateView.as_view(), name='oferta_aktualizuj'),
    path('oferta/<int:pk>/usun', OfertaDeleteView.as_view(), name='oferta_usun'),
    path('post/<int:pk>/komantarz', KomentarzCreateView.as_view(), name='komentarz_utworz'),
    path('komantarz/<int:pk>/aktualizuj', KomentarzUpdateView.as_view(), name='komentarz_aktualizuj'),
    path('komantarz/<int:pk>/usun', KomentarzDeleteView.as_view(), name='komentarz_usun'),
]

oferty/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

TYP_POMOCY = (
    ('NM','Nauka do matury'),
    ('NS','Nauka do sprawdzianu'),
    ('NL','Nauka do lekcji'),
)

TYP_OGLOSZENIA = (
    ('SP', 'Szukam pomocy'),
    ('OP', 'Oferuję pomoc'),
)

PRZEDMIOT = (
    ('P','Polski'),
    ('M','Matematyka'),
    ('F','Fizyka'),
    ('I','Informatyka'),
    ('A','Angielski'),
)


class Oferta(models.Model):
    tytul = models.CharField(max_length=80)
    tresc = models.TextField()
    przedmiot = models.CharField(choices=PRZEDMIOT, max_length=1)
    typ_ogloszenia = models.CharField(choices=TYP_OGLOSZENIA, max_length=2)
    typ_pomocy = models.CharField(choices=TYP_POMOCY, max_length=2)
    data = models.DateTimeField(default=timezone.now)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Oferty"

    def __str__(self):
        return self.tytul + '_' + self.autor.username

	def get_absolute_url(self):
        return reverse('oferta_szczegoly', kwargs={'pk': self.pk})

class Komentarz(models.Model):
    oferta = models.ForeignKey(Oferta, on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE, max_length=200)
    tresc = models.TextField()
    data = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = "Komentarze"

    def get_absolute_url(self):
        return reverse('komentarz_utworz', kwargs={'pk': self.pk})

    def __str__(self):
        return self.tresc 

oferty/views.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Oferta, Komentarz
from django.views.generic import ListView, DetailView, CreateView,\
                                UpdateView, DeleteView

def glowna(request):
    lista = Oferta.objects.all().order_by('-data')
    zapytanie = request.GET.get('q')
    print(zapytanie)
    if zapytanie:
        lista = Oferta.objects.filter(Q(tytul__icontains=zapytanie)).distinct()

    paginator = Paginator(lista, 10)
    strona = request.GET.get('page')
    try:
        oferty = paginator.page(strona)
    except PageNotAnInteger:
        oferty = paginator.page(1)
    except EmptyPage:
        oferty = paginator.page(paginator.num_pages)

    context = {
        'lista': lista,
    	'oferty': oferty
    }

    return render(request, 'oferty/strona_glowna.html', context)

class OfertaDetailView(DetailView):
    model = Oferta

    def get_context_data(self, **kwargs):
        context = super(OfertaDetailView, self).get_context_data(**kwargs)
        context['komentarze'] = Komentarz.objects.filter(oferta=self.kwargs.get('pk'))
        return context


class OfertaCreateView(LoginRequiredMixin, CreateView):
    model = Oferta
    fields = ['tytul', 'tresc', 'przedmiot', 'typ_ogloszenia', 'typ_pomocy']

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)


class OfertaUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Oferta
    fields = ['tytul', 'tresc']

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)

    def test_func(self):
        oferta = self.get_object()
        if self.request.user == oferta.autor:
            return True
        return False


class OfertaDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Oferta
    success_url = '/'

    def test_func(self):
        oferta = self.get_object()
        if self.request.user == oferta.autor:
            return True
        return False


class KomentarzCreateView(LoginRequiredMixin, CreateView):
    model = Komentarz
    fields = ['tresc']

    def form_valid(self, form, **kwargs):
        oferta = get_object_or_404(Oferta, pk=self.kwargs.get('pk'))
        form.instance.autor = self.request.user
        form.instance.oferta = oferta
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        pk = self.object.oferta.pk
        return reverse('oferta_szczegoly', kwargs={'pk': pk})


class KomentarzUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Komentarz
    fields = ['tresc']

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)

    def test_func(self):
        komentarz = self.get_object()
        if self.request.user == komentarz.autor:
            return True
        return False

    def get_success_url(self, **kwargs):
        pk = self.object.oferta.pk
        return reverse('oferta_szczegoly', kwargs={'pk': pk})


class KomentarzDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Komentarz

    def get_success_url(self, **kwargs):
        pk = self.object.oferta.id
        return reverse('oferta_szczegoly', kwargs={'pk': pk})

    def test_func(self):
        komentarz = self.get_object()
        if self.request.user == komentarz.autor:
            return True
        return False

oferty/templates/oferty/komentarz_confirm_delete.html
{% extends "oferty/podstawowy.html" %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class=" col-10 p-0 my-4 shadow mx-auto">
            <div class="col-12 custom-bg-dark p-2">
                <p class="mr-2"
                   style="color: #EE3733; text-transform: uppercase; font-weight: 900; font-size: 15px;"
                >Usuń swój komentarz</p>
            </div>
        <div class="col-12 p-4">
                <h2>Jesteś pewny że chcesz usunąć komentarz?</h2>
                <button class="btn btn-danger" type="submit">Tak, Usuń</button>
                <a class="btn btn-danger" href="{% url 'oferta_szczegoly' komentarz.oferta.id %}">Anuluj</a>
            </div>
        </div>
    </form>
{% endblock content %} 

oferty/templates/oferty/komentarz_form.html
{% extends 'oferty/podstawowy.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class=" col-10 p-0 my-4 shadow mx-auto">
            <div class="col-12 custom-bg-dark p-2">
                <p class="mr-2"
                   style="color: #EE3733; text-transform: uppercase; font-weight: 900; font-size: 15px;"
                >Dodaj Komentarz</p>
            </div>
            <div class="col-12 p-4">
                <form method="POST" class="post-form">{% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="save btn btn-danger">Stwórz</button>
                </form>
            </div>
        </div>
    </form>
    
{% endblock %} 

oferty/templates/oferty/oferta_confirm_delete.html
{% extends "oferty/podstawowy.html" %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class=" col-10 p-0 my-4 shadow mx-auto">
            <div class="col-12 custom-bg-dark p-2">
                <p class="mr-2"
                   style="color: #EE3733; text-transform: uppercase; font-weight: 900; font-size: 15px;"
                >Usuń swoją ofertę</p>
            </div>
            <div class="col-12 p-4">
                <h2>Jesteś pewny że chcesz usunąć ofertę "{{ object.tytul }}"</h2>
                <button class="btn btn-danger" type="submit">Tak, Usuń</button>
                <a class="btn btn-danger" href="{% url 'oferta_szczegoly' object.id %}">Anuluj</a>
            </div>
        </div>
    </form>
{% endblock content %} 

oferty/templates/oferty/oferta_detail.html
{% extends "oferty/podstawowy.html" %}
{% block content %}
    <div class=" col-10 p-0 my-4 shadow mx-auto">
        <div class="col-12 custom-bg-dark p-3">
            <a class="mr-2"
               style="color: #EE3733; text-transform: uppercase; font-weight: 900; font-size: 15px;"
               href="{% url 'profil_innego_uzytkownika' oferta.autor.id %}">{{ autor.get_full_name|default:oferta.autor }}</a>
            <small class="text-muted">{{ oferta.data|date:"F d, Y" }}</small>
            {% if oferta.autor == request.user %}
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'oferta_aktualizuj' object.id %}">Aktualizuj</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'oferta_usun' object.id %}">Usuń</a>
            {% endif %}
        </div>
        <div class="col-12">
            <h2><p class="article-title">{{ object.tytul }}</p></h2>
            <p class="article-content pb-3 px-3">{{ object.tresc }}</p>
        </div>
    </div>
  
  {% if user.is_authenticated %}
        <hr>
        <a class="btn btn-danger" href="{% url 'komentarz_utworz' object.id %}">Dodaj Komentarz</a>
    {% endif %}
    <hr>
    <h3> komentarze: {{ komentarze.count }}</h3>
    {% for komentarz in komentarze.all %}
        <div class=" col-6 p-0 my-4 shadow">
            <div class="col-12 custom-bg-dark p-1">
                <img class="rounded-circle article-img" src="{{ komentarz.autor.profil.zdjecie.url }}"
                     style="max-width: 50px; max-height: 50px;">
                <a class="mr-2"
                   style="color: #EE3733; text-transform: uppercase; font-weight: 900; font-size: 15px;"
                   href="{% url 'profil_innego_uzytkownika' komentarz.autor.id %}">{{ komentarz.autor.get_full_name|default:komentarz.autor }}</a>
                <small class="text-muted">{{ komentarz.date|date:"d.m.Y" }}</small>
                {% if komentarz.autor == request.user %}
                    <a class="btn btn-sm mt-1 mb-1" href="{% url 'komentarz_aktualizuj' komentarz.pk %}">
                        <span><i class="fas fa-pen text-danger d-flex "></i></span>
                    </a>
                    <a class="btn btn-sm mt-1 mb-1" href="{% url 'komentarz_usun' komentarz.pk %}">
                        <span><i class="fas fa-trash-alt text-danger d-flex "></i></span>
                    </a>
                {% endif %}
            </div>
            <div class="col-12">
                <p class="article-content p-3">{{ komentarz.tresc }}</p>
            </div>
        </div>
    {% endfor %}
{% endblock content %} 

oferty/templates/oferty/oferta_form.html
{% extends 'oferty/podstawowy.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class=" col-10 p-0 my-4 shadow mx-auto">
            <div class="col-12 custom-bg-dark p-2">
                <p class="mr-2"
                   style="color: #EE3733; text-transform: uppercase; font-weight: 900; font-size: 15px;"
                >Utwórz Ofertę</p>
            </div>
            <div class="col-12 p-4">
                {{ form|crispy }}
                <button class="btn btn-danger" type="submit">Utwórz</button>
            </div>
       </div>
    </form>

{% endblock %} 

oferty/templates/oferty/podstawowy.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'oferty/style.css' %}">

    {% if title %}
        <title>Pomoc - {{ title }}</title>
    {% else %}
        <title>Pomoc</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md  custom-bg-dark fixed-top ">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'glowna' %}">Strona Główna</a>
                </div>
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link text-white" href="{% url 'oferta_utworz' %}">Nowa Oferta</a>
                        <a class="nav-item nav-link text-white" href="{% url 'profil' %}">Profil</a>
                        <a class="nav-item nav-link text-white" href="{% url 'wyloguj' %}">Wyloguj</a>
                    {% else %}
                        <a class="nav-item nav-link text-white" href="{% url 'zaloguj' %}">Loguj</a>
                        <a class="nav-item nav-link text-white" href="{% url 'zarejestruj' %}">Rejestracja</a>
                    {% endif %}

            </div>
          </div>
        </div>
      </nav>
	</header>
	<main role="main" class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="container mt-5 pt-4">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{ message|safe }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            {% block content %}{% endblock %}
        </div>
      </div>
    </main>
	
	     <footer class="mt-5 py-5 custom-bg-dark">
    <div class="container">
        <div class="row">
           <div class="col-8 mt-md-0 mt-3 text-white mx-auto text-center">
                <h5 class="text-uppercase font-weight-bold text-white">Pomoc!</h5>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita sapiente sint, nulla, nihil
                    repudiandae commodi voluptatibus corrupti animi sequi aliquid magnam debitis, maxime quam recusandae
                    harum esse fugiat. Itaque, culpa?</p>
                <p>Nie masz jeszcze konta?<span class="ml-3"><a class="btn btn-outline-light"
                                                                href="{% url 'zarejestruj' %}">Dołącz do nas!</a></span>
                </p>
            </div>
        </div>
    </div>
      <hr style="border: 1px solid white;">
      <p class="m-0 text-center text-white">Copyright &copy; 2020</p>
  </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html> 

oferty/templates/oferty/strona_glowna.html
{% extends "oferty/podstawowy.html" %}
{% load static %}
{% block content %}
    <div class="row"></div>
    <div class="row align-items-center my-5 shadow custom-bg-danger">
        <div class="col-7 d-none d-lg-block" style="padding:0;">
            <img class="img-fluid mb-4 mb-lg-0" src="{% static 'oferty/img/bg.jpg' %}"
                 style=" max-height: 600px;" alt="">
        </div>
        <div class="col-lg-5 ">
            <h1 class="font-weight-light p-3"
                style=" text-transform: uppercase; margin-bottom: 0.5rem; font-size: 48px; color: #000000; line-height: 1.3; font-weight: 900;">
                Wspólna nauka w CG!</h1>
            <hr style="border: black solid 2px;" class="mr-5">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                A assumenda dignissimos ducimus iure magni numquam odio, officia perspiciatis placeat quae, quam quas
                quisquam
                reprehenderit sapiente sed suscipit vero! Eius, perspiciatis.</p>
            <a class="btn btn-lg btn-dark custom-bg-dark my-3" href="{% url 'zarejestruj' %}">Dołącz do nas!</a>
        </div>
    <div class="row">
        <div class="col-lg-8 col-12">
            {% for oferta in oferty %}
                <div class="row">
                    <div class=" col-7 p-0 my-4 shadow">
                        <div class="col-12 custom-bg-dark p-3">
                            <a class="mr-2"
                               style="color: #EE3733; text-transform: uppercase; font-weight: 900; font-size: 15px;"
                               href="{% url 'profil_innego_uzytkownika' oferta.autor.id %}">{{ oferta.autor.get_full_name|default:oferta.autor }}</a>
                            <small class="text-muted">{{ oferta.data|date:"F d, Y" }}</small></div>
                        <div class="col-12">
                            <h2><a class="article-title"
                                   href="{% url 'oferta_szczegoly' oferta.id %}">{{ oferta.tytul }}</a></h2>
                            <p class="article-content">{{ oferta.tresc }}</p>
                        </div>
                    </div>
                    <div class="col-5 custom-bg-danger p-4 shadow">
                        <h5 class="article-title"> Dodatkowe informacje:</h5>
                        <ul>
                            <li>{{ oferta.get_typ_ogloszenia_display }}</li>
                            <li>{{ oferta.get_przedmiot_display }}</li>
                            <li>{{ oferta.get_typ_pomocy_display }}</li>
                        </ul>
                    </div>
                </div>
                <hr style="border: black solid 1px;" class="mx-5">
            {% endfor %}
        </div>
        <div class="col-md-4">

            <div class="card shadow">
                <h5 class="card-header custom-bg-dark shadow" style=" color: white">Search</h5>
                <div class="card-body">
                    <div class="input-group">
                        <form method="GET" class="form-inline">
                            <div class="md-form my-0">
                                <input class="form-control mr-sm-2" type="text" name="q" value="{{ request.GET.q }}"
                                       type="text" placeholder="Szukaj..." aria-label="Search">
                                <span class="input-group-btn"><button class="btn btn-danger" type="submit"><i
                                        class="fas fa-search"></i></button>
                                </span>
                            </div>
                    </div>
                </div>
        </div>

    </div>
    {% if oferty.has_other_pages %}
        <nav class="d-flex justify-content-center">
            <ul class="pagination">
                {% if oferty.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=
                    {{ oferty.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% endif %}
                {% for num in oferty.paginator.page_range %}
                    {% if oferty.number == num %}
                        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% elif num > oferty.number|add:'-1' and num < oferty.number|add:'1' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if oferty.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page=
                {{ oferty.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock content %}